I think this is the best way
josehpena/WeeklyChallenge4 pull request #5
Opened 2021-05-26 16:48 UTC by josehpena

2021-05-26 16:51 UTC, josehpena commented on challenge/src/test/java/com/ifood/challenge/ChallengeApplicationTests.java
> +		assertThrows(IllegalArgumentException.class,() -> { locationService.getLocation(-1);});
Vi alguns exemplos, mas não sei se posso utilizar assim.

2021-05-26 16:58 UTC, josehpena commented on challenge/src/test/java/com/ifood/challenge/ChallengeApplicationTests.java
> +		assertThrows(IllegalArgumentException.class,() -> { locationService.getLocation(-1);});
Uma explicação com alguns exemplos que utilizei para entender o funcionamento do assertThrows foi esse https://howtodoinjava.com/junit5/expected-exception-example/

2021-05-26 22:01 UTC, ratoji requested changes

2021-05-26 22:01 UTC, ratoji commented on challenge/src/test/java/com/ifood/challenge/ChallengeApplicationTests.java
> +		assertThrows(IllegalArgumentException.class,() -> { locationService.getLocation(-1);});
Vamos lá, aqui estamos confundindo as coisas. A ideia é testar a API, então não faz sentido chamar o service diretamente.

A maneira de testar a API é basicamente chamar e verificar que ela devolve o código de retorno esperado.

Vou comentar isso na API.

2021-05-26 22:01 UTC, ratoji commented on challenge/src/main/java/com/ifood/challenge/location/LocationController.java
>          return locationService.getLocation(number);
Agora que `LocationService.getLocation()` joga uma `IllegalArgumentException`, precisaríamos aqui capturar essa exceção pra poder responder com o código HTTP adequado.

Uma vez capturada, podemos usar `ResponseEnity` para responder com HTTP 200 (OK) ou 400 (bad request):
https://www.baeldung.com/spring-response-entity

2021-05-27 17:56 UTC, ratoji approved these changes
ok!

2021-05-27 18:00 UTC, merged